### ISSUE TITLE
forge web start failed 

### ISSUE THREAD

**Issue by humyna** [ArcBlock/forge-js#267]
s1.forge reset
s2.forge init 
s3.forge start 
s4.forge web start
![image](https://user-images.githubusercontent.com/2505439/57456673-8d272f00-72a0-11e9-98f1-8cdf1fae1bfb.png)
![image](https://user-images.githubusercontent.com/2505439/57456902-1179b200-72a1-11e9-9a96-bbee555045bc.png)

**Comment by wangshijun** [comment]
Root cause for this issue is that developer did an incomplete setup of forge-cli and forge, and forge-cli did not enforcea forge component binary existence before executing it.

`forge web` related commands will exit if the `forge_web` binary is not found.

#271 

Closing now!

**Comment by wangshijun** [comment]
fix should be published in `@arcblock/forge-cli` v0.26.3
