### ISSUE TITLE
forge create-project no need to require forge to be started

### ISSUE THREAD

**Issue by tyrchen** [ArcBlock/forge-js#286]
Now if want to create a new project, forge-cli will give an error if forge is not started. However, creating a project may not necessarily be related to the local forge - if the user uses a remote endpoint then she doesn't need the support from the local node.

```
08:24 $ forge create-project aaa
✖ forge is not started yet!
ℹ Please run forge start first!
```

And create project should just create skeleton and install deps, it should not be involved with calling forge API to do something (is it because you'd retrieve chain id?).

**Comment by wangshijun** [comment]
Because the application requires an forge graphql endpoint to talk to, in next version, we may ask user to input an endpoint and write that into config.

Leave all the configuration to the starters may make it difficult for them to wrap things together.

**Comment by wangshijun** [comment]
#289

**Comment by wangshijun** [comment]
`forge create-project` now requires a valid graphql endpoint, not require a running forge node.

**Comment by wangshijun** [comment]
https://github.com/ArcBlock/forge-react-starter/pull/3

**Comment by wangshijun** [comment]
https://github.com/ArcBlock/forge-react-starter/issues/1
