### ISSUE TITLE
My chain has moderator but upgrade failed

### ISSUE THREAD

**Issue by tyrchen** [ArcBlock/forge-js#376]
```
iex(forge-forge-c21f969b5f03d33d43e04f8f136e7682@localhost)3> ForgeSdk.get_forge_state
%ForgeAbi.ForgeState{
  account_config: %{
    "moderator" => %ForgeAbi.AccountConfig{
      address: "z11LFAwVJ4NdAHVVbVeNJsJ4nxHH3UJ8Fusy",
      balance: %ForgeAbi.BigUint{value: <<0>>},
      pk: "ABCcGxD3sIzn5qLaxXn0ZPzCJxKsglEobuJOZwEfIoY"
    },
    "token_holder" => %ForgeAbi.AccountConfig{
      address: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
      balance: %ForgeAbi.BigUint{value: <<238, 107, 40, 0>>},
      pk: ""
    }
  }
```

The moderator in my configuration is z11LFAwVJ4NdAHVVbVeNJsJ4nxHH3UJ8Fusy.

However, when I run upgrade:

```
$ /usr/local/bin/forge upgrade
ℹ Connect to grpc endpoint: tcp://127.0.0.1:28210
ℹ moderator address z1iNCeMmHUqxG6xUmfS7rj59o8AJRT7YSkS
✔ moderator declared on chain
? To which version your want to upgrade? (Use arrow keys)
❯ 0.38.6
```

It prompt me the address is "z1iNCeMmHUqxG6xUmfS7rj59o8AJRT7YSkS", which is wrong.

**Comment by wangshijun** [comment]
@tyrchen Is the forge configure file generated by forge-cli? do you have `FORGE_MODERATOR_SK` in env? does the moderator address and pk match with those generated from your `FORGE_MODERATOR_SK`? if they do not match, the upgrade will fail.

However, forge-cli should be smart enough to ensure that the moderator match in env and forge state before doing anything.

**Comment by wangshijun** [comment]
resolved in forge-cli
