### ISSUE TITLE
make did-auth work smoothly in both mobile and desktop env

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/forge-js#436]
Issues

- Token 的类别
    - sessionToken：用户使用 dapp 期间的认证标识，能够查到用户信息
    - actionToken：用户在 dapp 中做了某次操作的标识，能够查到操作相关的信息

- 现状：
    - did-auth 成功之后 pc 端没有回调，只能靠轮询或 socket 来拿到 action 的数据
    - did-auth 成功之后 mobile 端有回调，靠的是 url 参数来拿到 session 数据，action 数据拿不到

目标：不论跨不跨浏览器，sessionToken 和 actionToken 都能保持，就是说在用户看来，流程是完整

疑问：能不用只用 actionToken 就能查到 session 信息，也能查到 action 信息

- 不跨浏览器
    - 如果没有登录，肯定先要求登录
    - 如果登录了，LocalStorage 里面有 loginToken，需要解决的问题就是 actionToken 回调时成功的状态
- 跨浏览器：Chrome --> Safari
    - 如果 Chrome 没有登录，Safari 不管有没有登录，肯定要求先在 Chrome 登录
    - 如果 Chrome 登录了，Safari 没登录，怎么办？
    - 如果 Chrome 登录了，Safari 也登录了，只需要解决 actionToken 的问题

TODO:

- [ ] token storage 的索引，自动删除机制【中优】
- [ ] action token 移动端的传递问题，建议封装在 `@arcblock/did-auth` 里面，使用 `callbackParams` 【高优】
- [ ] action token 如何通过它拉取 session 数据的问题【中优】
- [ ] 前端如何根据 action-token 恢复状态【高优】

**Comment by polunzh** [comment]
我说下关于`前端如何根据 action-token 恢复状态`的想法.
因为我们添加了`自定义成功后显示消息`的功能，所以对于 DID Auth 组件来说，完成授权(成功)后的处理分为两种情况:
1. 需要在恢复 Auth 组件的展示，比如`自定义成功后显示消息`的;
2. 只需要处理成功后的业务逻辑，不需要恢复组件的展示。
对于第二种情况来说比较好处理，我们现在的处理方式只要加上跨浏览器支持就行了。
但是第一种来说可能比较复杂, 因为我觉得很难跨浏览器保持组件本身的状态，从而恢复组件的展示。

**Comment by mave99a** [comment]
跨浏览器这件事情，我其实觉得好像不太应该。 这甚至有可能有安全隐患，也会过于复杂。 

为什么需要跨浏览器这个问题呢？ 是android上经常出现这个问题？ 其他应用一般如何解决呢？

**Comment by mave99a** [comment]
@jonathanlu813 问题的关键是如何能让universal link 跳转回到原来的页面？ 而不是打开新页面？ 我一直以为是回到了原来页面的。 

@NateRobinson @PaperHS  android上也有一样的问题。 

如果我们确信没有办法可以调整回去，那么我们得想其他的思路。

**Comment by mave99a** [comment]
@jonathanlu813 能在代码里要求“back to previous app”吗？ 如果能的话，这个问题也能解决，

**Comment by mave99a** [comment]
实在不行，我们让用户点击上角回去也不失为一种办法。

**Comment by wangshijun** [comment]
钱包下个版本会支持 webview，整个流程会很流畅，关闭该问题。
