### ISSUE TITLE
support display interface for all NFT

### ISSUE THREAD

**Issue by PaperHS** [ArcBlock/forge-js#450]
support display interface for all NFT

**Comment by PaperHS** [comment]
SVG support 
iOS:
path
line
rect
circle
ellipse
polygon
image
text
use
title
desc
mask
clip
filter
radialGradient
linearGradient
g
style
defs

Android:
svg,
      a,
      circle,
      clipPath,
      defs,
      desc,
      ellipse,
      g,
      image,
      line,
      linearGradient,
      marker,
      mask,
      path,
      pattern,
      polygon,
      polyline,
      radialGradient,
      rect,
      solidColor,
      stop,
      style,
      SWITCH,
      symbol,
      text,
      textPath,
      title,
      tref,
      tspan,
      use,
      view,

Android 支持除了filter之外的所有iOS字段，所以iOS Android共同支持的字段为
path
line
rect
circle
ellipse
polygon
image
text
use
title
desc
mask
clip
filter
radialGradient
linearGradient
g
style
defs

**Comment by wangshijun** [comment]
#453
