### ISSUE TITLE
我在使用forge web提供的的查询时遇到了问题

### ISSUE THREAD

**Issue by A-new-b** [ArcBlock/forge-js#472]
我在forge web提供的qurey中使用getBlock函数查询链高分别为48923，48924的区块时，觉得前后的hash值没有对上，如图所示

![48923](https://user-images.githubusercontent.com/43344034/87666579-6d8c7000-c79b-11ea-9880-24659ade5b75.png)
![48924](https://user-images.githubusercontent.com/43344034/87666583-6f563380-c79b-11ea-8d93-741d3357f353.png)
48923的apphash并非48924的lastBlockId属性的hash属性，我想询问这是什么原因，48924的lastBockId代表了什么意思

**Comment by NateRobinson** [comment]
你好，请问你是否是想通过这个 hash 来做前后 Block 的验证，如果只是遍历的话，用 height 做递减就可以完成了？

**Comment by A-new-b** [comment]
是的，我们想通过这个hash来做为验证，但是通过forge web 再后一个区块中似乎没有找到前一个区块的hash值（在上图中），请问这是什么原因？

**Comment by A-new-b** [comment]
> 
> 
> 你好，请问你是否是想通过这个 hash 来做前后 Block 的验证，如果只是遍历的话，用 height 做递减就可以完成了？

是的，我们想通过这个hash来做为验证，但是通过forge web 在后一个区块中似乎没有找到前一个区块的hash值（在上图中），请问这是什么原因？按道理这不应该发生

**Comment by wangshijun** [comment]
@A-new-b 你所看到的 `lastBlockId.hash` 是共识引擎层 `tendermint` 存储的数据，在 forge 里面这个 hash 的计算方式略有不同。

因为 Forge 架构上是分层的，简化理解的话，从上到下是 “API 层”、“交易处理层”、“共识引擎层”，目前版本的 getBlock 里面返回的数据里面不包含上 1 个区块的 block hash，Forge 状态数据库里面存储的 Block 结构和共识引擎层略不同，而你通过接口层拿到的数据是直接从交易处理层读取出来返回的。

从分层的角度，前后区块之间的关联在共识引擎层、和交易处理层都是是可以验证的，验证方法分别为：

- 共识引擎层：可以直接使用 tendermint 提供的 rpc 接口把区块的数据拉回来，比对关联字段，详见下面的几个附件
- 交易处理层：需要把 block 数据按 forge-abi 里面定义的 `Block` 结构体编码成二进制，求 sha256 后关联共识引擎层的数据去比对，这块后续我们可以考虑扩展下 `getBlock` 在里面包含计算好的当前块和上一个块的 block hash


以下是 xenon 链 3077840、3077839、3077838 三个区块在共识引擎层的数据供参考：


[tendermint-blocks.zip](https://github.com/ArcBlock/forge-js/files/5049102/tendermint-blocks.zip)

当然，这个验证过程你也可以在本地进行：

1. 使用 forge-cli 启动一条测试链
2. 等待出几个区块，不论是不是孔快都 OK
3. 找到链节点配置文件里面的 rpc 端口：`cat ~/.forge_chains/forge_xxx/forge_release.toml | grep sock_rpc`
4. 然后 `curl --insecure https://127.0.0.1:28221/block?height=xxx` 就能拿到共识层，注意端口号需要替换成步骤三找到的
5. 多拉几个块的数据回来，然后验证他们

**Comment by A-new-b** [comment]
> @A-new-b 你所看到的 `lastBlockId.hash` 是共识引擎层 `tendermint` 存储的数据，在 forge 里面这个 hash 的计算方式略有不同。
> 
> 因为 Forge 架构上是分层的，简化理解的话，从上到下是 “API 层”、“交易处理层”、“共识引擎层”，目前版本的 getBlock 里面返回的数据里面不包含上 1 个区块的 block hash，Forge 状态数据库里面存储的 Block 结构和共识引擎层略不同，而你通过接口层拿到的数据是直接从交易处理层读取出来返回的。
> 
> 从分层的角度，前后区块之间的关联在共识引擎层、和交易处理层都是是可以验证的，验证方法分别为：
> 
>     * 共识引擎层：可以直接使用 tendermint 提供的 rpc 接口把区块的数据拉回来，比对关联字段，详见下面的几个附件
> 
>     * 交易处理层：需要把 block 数据按 forge-abi 里面定义的 `Block` 结构体编码成二进制，求 sha256 后关联共识引擎层的数据去比对，这块后续我们可以考虑扩展下 `getBlock` 在里面包含计算好的当前块和上一个块的 block hash
> 
> 
> 以下是 xenon 链 3077840、3077839、3077838 三个区块在共识引擎层的数据供参考：
> 
> [tendermint-blocks.zip](https://github.com/ArcBlock/forge-js/files/5049102/tendermint-blocks.zip)
> 
> 当然，这个验证过程你也可以在本地进行：
> 
>     1. 使用 forge-cli 启动一条测试链
> 
>     2. 等待出几个区块，不论是不是孔快都 OK
> 
>     3. 找到链节点配置文件里面的 rpc 端口：`cat ~/.forge_chains/forge_xxx/forge_release.toml | grep sock_rpc`
> 
>     4. 然后 `curl --insecure https://127.0.0.1:28221/block?height=xxx` 就能拿到共识层，注意端口号需要替换成步骤三找到的
> 
>     5. 多拉几个块的数据回来，然后验证他们

确实如您所说，我们看见了前后对应的id，多谢您的帮助
