### ISSUE TITLE
forge-util v1.5.8 版本下面的依赖  multibase 会导致其他项目的 test 失败

### ISSUE THREAD

**Issue by NateRobinson** [ArcBlock/forge-js#494]
![截屏2021-03-02 下午6 09 53](https://user-images.githubusercontent.com/12446758/109632910-7ee78880-7b82-11eb-8f23-476d4d416c35.png)

可能相关的 issue: https://github.com/multiformats/js-multibase/issues/66

**Comment by wangshijun** [comment]
fixed https://github.com/ArcBlock/forge-webapp/commit/0a5214563624ceb742ca71a4d6070be89699d710
